- id: porch_sunset_lights
  alias: Porch lights on at Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    data:
      brightness_pct: 100
      entity_id:
        - group.porch_lights

- id: sunset_lights
  alias: Lights on at Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: home
  action:
    service: homeassistant.turn_on
    data:
      brightness_pct: 100
      entity_id:
        - group.hallway
        - group.robot_lab
        - group.bedroom

- id: arrive_lights
  alias: Lights on when we get home
  trigger:
    platform: state
    entity_id: group.all_devices
    to: home
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: homeassistant.turn_on
    data:
      brightness_pct: 100
      entity_id:
        - group.porch_lights
        - group.hallway

- id: bedtime
  alias: Lights down for bedtime
  trigger:
    platform: time
    hours: 22
    minutes: 0
    seconds: 0
  action:
    service: homeassistant.turn_on
    data:
      brightness_pct: 10
      entity_id:
        - group.hallway

- id: nighttime
  alias: Lights off at 11pm
  trigger:
    platform: time
    hours: 23
    minutes: 0
    seconds: 0
  action:
    service: homeassistant.turn_off
    data:
      entity_id:
        - group.porch_lights
        - light.living_room

- id: weather
  alias: Color loop bed if rain
  trigger:
    platform: time
    hours: [6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    minutes: 0
    seconds: 0
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: yweather.weather_condition
        state: 'rainy'
      - condition: state
        entity_id: yweather.weather_condition
        state: 'pouring'
  action:
    service: homeassistant.turn_on
    data:
      effect: colorloop
      entity_id:
        - light.bed

- id: weather_unusual
  alias: Set bed to red if unusual weather
  trigger:
    platform: time
    hours: [6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    minutes: 0
    seconds: 0
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: yweather.weather_condition
        state: 'hail'
      - condition: state
        entity_id: yweather.weather_condition
        state: 'lightning'
      - condition: state
        entity_id: yweather.weather_condition
        state: 'lightning-rainy'
      - condition: state
        entity_id: yweather.weather_condition
        state: 'snowy'
      - condition: state
        entity_id: yweather.weather_condition
        state: 'snowy-rainy'
      - condition: state
        entity_id: yweather.weather_condition
        state: 'exceptional'
  action:
    service: homeassistant.turn_on
    data:
      effect: colorloop
      entity_id:
        - light.bed

- id: driveway_timer
  alias: Turn off driveway after 10 minutes
  trigger:
    - platform: state
      entity_id: light.driveway
      to: 'on'
      for:
        minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: light.driveway
