- id: porch_sunset_lights
  alias: Porch lights on at Sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    data:
      brightness_pct: 100
      entity_id:
        - group.porch_lights

- id: sunset_lights
  alias: Lights on at Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: home
  action:
    service: homeassistant.turn_on
    data:
      brightness_pct: 100
      entity_id:
        - group.hallway
        - group.robot_lab
        - group.bedroom

- id: arrive_lights
  alias: Lights on when we get home
  trigger:
    platform: state
    entity_id: group.all_devices
    to: home
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: homeassistant.turn_on
    data:
      brightness_pct: 100
      entity_id:
        - group.porch_lights
        - group.hallway

- id: bedtime
  alias: Lights down for bedtime
  trigger:
    platform: time
    hours: 22
    minutes: 0
    seconds: 0
  action:
    service: homeassistant.turn_on
    data:
      brightness_pct: 10
      entity_id:
        - group.hallway

- id: nighttime
  alias: Lights off at 11pm
  trigger:
    platform: time
    hours: 23
    minutes: 0
    seconds: 0
  action:
    service: homeassistant.turn_off
    data:
      entity_id:
        - group.porch_lights
        - light.living_room
