- id: porch_sunset_lights
  alias: Porch lights on at Sunset
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: switch.turn_on
    data: {}
    target:
      device_id:
      - 7171da74eb678558e84b97f23ea8c79e
      - 377a2f4dd175686d4152cbbc39103dd2
  mode: single
- id: sunset_lights
  alias: Lights on at Sunset
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.austin
      state: home
    - condition: state
      entity_id: person.katrina
      state: home
    - condition: state
      entity_id: input_boolean.vacation
      state: 'on'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      color_temp: 270
      transition: 300
    target:
      area_id: a7e7176a46f44fccb565020478a1496b
      entity_id:
      - light.hall_light
      - light.stair_light
      - light.kitchen
  - service: light.turn_on
    data:
      brightness_pct: 50
      transition: 300
    target:
      entity_id:
      - light.living_room_lights
      - light.living_room_walkway
  mode: single
- id: arrive_lights
  alias: Lights on when we get home
  trigger:
  - platform: state
    entity_id:
    - person.austin
    - person.katrina
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: light.turn_on
    data:
      color_temp: 300
      brightness_pct: 100
    target:
      area_id: a7e7176a46f44fccb565020478a1496b
      entity_id:
      - light.hall_light
      - light.stair_light
      - light.kitchen
      - light.living_room_walkway
  mode: single
- id: bedtime
  alias: Lights down for bedtime
  trigger:
  - platform: time
    at: '22:00:00'
  action:
  - service: script.turn_down_lights
    data: {}
  mode: single
- id: nighttime
  alias: Lights off at 11pm
  trigger:
  - platform: time
    at: '23:00:00'
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id:
      - 377a2f4dd175686d4152cbbc39103dd2
      - 7171da74eb678558e84b97f23ea8c79e
  mode: single
- id: driveway_timer
  alias: Turn off driveway after 10 minutes
  trigger:
  - platform: state
    entity_id: switch.leviton_dz15s_1bz_decora_smart_switch_switch
    to: 'on'
    for: 0:10:00
  action:
  - service: switch.turn_off
    entity_id: switch.leviton_dz15s_1bz_decora_smart_switch_switch
  mode: single
- id: '1609020537681'
  alias: Fans on at 5pm
  description: ''
  trigger:
  - platform: time
    at: '17:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.fans
  mode: single
- id: '1609020585677'
  alias: Fans off at 8pm
  description: ''
  trigger:
  - platform: time
    at: '20:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.fans
  mode: single
- id: '1654842028622'
  alias: Espresso on for wakeup
  description: ''
  trigger:
  - platform: time
    at: input_datetime.espresso_time
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'off'
  action:
  - type: turn_on
    device_id: e0a8d506052e4ab89dc725421ddf9f91
    entity_id: switch.espresso
    domain: switch
  mode: single
- id: '1654842059627'
  alias: Espresso off at 5pm
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: e0a8d506052e4ab89dc725421ddf9f91
    entity_id: switch.espresso
    domain: switch
  mode: single
- id: '1656397296999'
  alias: Toe Kicks on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 60
      brightness_pct: 50
    target:
      device_id: f5296158d4fb4860796c2947a093ccaa
  mode: single
- id: '1656397365177'
  alias: Toe kicks low
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 60
      brightness_pct: 20
    target:
      device_id: f5296158d4fb4860796c2947a093ccaa
  mode: single
- id: '1656397536048'
  alias: Toe kicks off
  description: ''
  trigger:
  - platform: time
    at: '23:30:00'
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 30
    target:
      device_id: f5296158d4fb4860796c2947a093ccaa
  mode: single
- id: '1656398231281'
  alias: Wake up
  description: ''
  trigger:
  - platform: time
    at: input_datetime.wakeup
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 300
      brightness_pct: 100
      color_temp: 299
    target:
      area_id: a7e7176a46f44fccb565020478a1496b
      device_id:
      - 08684f8fb3a4d2131a1de46a184c9893
      - 6fd7e8960856e5a726b5c44a2810a402
      - 463917272dafea89c447c90046d776ac
  mode: single
- id: '1663601026179'
  alias: Update espresso time
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_datetime.wakeup
  condition: []
  action:
  - service: input_datetime.set_datetime
    data:
      time: '{{ strptime(states(''input_datetime.wakeup''), ''%H:%M:%S'') - strptime(''30'',
        ''%M'') }}'
    target:
      entity_id: input_datetime.espresso_time
  mode: single
- id: '1663601520815'
  alias: Lights off on Vacation
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'on'
  action:
  - service: script.lights_off
    data: {}
  mode: single
