- id: porch_sunset_lights
  alias: Porch lights on at Sunset
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: homeassistant.turn_on
    data:
      brightness_pct: 100
      color_temp: 270
      entity_id:
      - group.porch_lights
      - light.entry_light
  - service: homeassistant.turn_on
    data:
      brightness_pct: 60
      entity_id:
      - light.carport
  mode: single
- id: sunset_lights
  alias: Lights on at Sunset
  trigger:
  - platform: sun
    event: sunset
    offset: -00:45:00
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.austin
      state: home
    - condition: state
      entity_id: person.katrina
      state: home
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
      color_temp: 270
      entity_id:
      - group.hallway
      - group.bedroom
      - light.living_room
      - light.dining_room
  - service: light.turn_on
    data:
      brightness_pct: 15
    entity_id: light.living_room_oros
  mode: single
- id: arrive_lights
  alias: Lights on when we get home
  trigger:
  - platform: state
    entity_id: person.austin, person.katrina
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: homeassistant.turn_on
    data:
      brightness_pct: 100
      color_temp: 270
      entity_id:
      - group.porch_lights
      - group.hallway
      - light.carport
      - light.dining_room
  mode: single
- id: bedtime
  alias: Lights down for bedtime
  trigger:
  - platform: time
    at: '21:30:00'
  action:
  - service: homeassistant.turn_on
    data:
      brightness_pct: 20
      color_temp: 270
      entity_id:
      - group.hallway
      - light.living_room
      - light.dining_room
  - service: light.turn_on
    data:
      brightness_pct: 1
    entity_id: light.living_room_oros
  mode: single
- id: nighttime
  alias: Lights off at 11pm
  trigger:
  - platform: time
    at: '23:00:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
      - group.porch_lights
      - group.living_room
      - light.carport
      - light.dining_room
  mode: single
- id: driveway_timer
  alias: Turn off driveway after 10 minutes
  trigger:
  - platform: state
    entity_id: switch.leviton_dz15s_1bz_decora_smart_switch_switch
    to: 'on'
    for: 0:10:00
  action:
  - service: switch.turn_off
    entity_id: switch.leviton_dz15s_1bz_decora_smart_switch_switch
  mode: single
- id: '1609020537681'
  alias: Fans on at 5pm
  description: ''
  trigger:
  - platform: time
    at: '17:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.fans
  mode: single
- id: '1609020585677'
  alias: Fans off at 8pm
  description: ''
  trigger:
  - platform: time
    at: '20:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.fans
  mode: single
- id: '1654842028622'
  alias: Espresso on at 6:30am
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition: []
  action:
  - type: turn_on
    device_id: e0a8d506052e4ab89dc725421ddf9f91
    entity_id: switch.espresso
    domain: switch
  mode: single
- id: '1654842059627'
  alias: Espresso off at 5pm
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: e0a8d506052e4ab89dc725421ddf9f91
    entity_id: switch.espresso
    domain: switch
  mode: single
