homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.4625
  longitude: -122.2405
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

default_config:

# logging setup
logger:
  default: info
  logs:
    #homeassistant.components.automation: debug
    #homeassistant.components.unifi: debug
    homeassistant.components.google: debug
    homeassistant.components.calendar.google: debug
    #homeassistant.components.unifi.device_tracker: debug
    #homeassistant.components.switch.unifi: debug

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Enable config UI
config:


# Enable scripts?
script: !include scripts.yaml

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#apcupsd:
#  host: 192.168.1.1

#asterisk:
#  host: arg
#  port: 5038
#  username: admin
#  password: !secret asterisk_password

#rainmachine:
#  controllers:
#    - ip_address: 192.168.1.16
#      password: !secret rainmachine_password

sensor:
  #- platform: apcupsd
  #  resources:
  #    - apc
  #    - date
  #    - hostname
  #    - upsname
  #    - upsmode
  #    - starttime
  #    - model
  #    - status
  #    - linev
  #    - loadpct
  #    - bcharge
  #    - timeleft
  #    - mbattchg
  #    - mintimel
  #    - maxtime
  # Asterisk VoIP phones
  #- platform: astext
  #  extension: 10
  #- platform: astext
  #  extension: 11
  #- platform: astext
  #  extension: 12
  # Weather conditions from personal weather station and weather forecast.
  #  - platform: wundergroundpws
  #    api_key: !secret wunderground_key
  #    pws_id: KCAPACIF183
  #    monitored_conditions:
  #     # Weather sensors
  #     - stationID
  #     - solarRadiation
  #     - uv
  #     - winddir
  #     - humidity
  #     - dewpt
  #     - heatIndex
  #     - windChill
  #     - precipTotal
  #     - precipRate
  #     - pressure
  #     - temp
  #     - windGust
  #     - windSpeed
  #     # Weather predictions
  #     - precip_1d
  #     - precip_chance_1d
  #     - temp_high_1d
  #     - temp_low_1d
  #     - wind_1d
  #     - weather_1d
  #     - weather_1n
  #     - weather_2d
  #     - weather_2n
  #     - weather_3d
  #     - weather_3n
  #     - weather_4d
  #     - weather_4n

hue:
  bridges:
    - host: 192.168.0.91
      allow_hue_groups: False

light:
  - platform: decora_wifi
    username: namniart@gmail.com
    password: !secret leviton_password

#tplink:
#  discovery: True

influxdb:
  host: 127.0.0.1
  port: 8086
  username: home_assistant
  password: home_assistant

google:
  client_id: !secret google_cal_client_id
  client_secret: !secret google_cal_client_secret

calendar:
  - platform: todoist
    token: !secret todoist_api_token

automation: !include automations.yaml
automation old: !include_dir_merge_list automations

#media_player:
#  - platform: yamaha
#    host: 192.168.1.63



group: !include groups.yaml
