homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 37.4625
  longitude: -122.2405
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# logging setup
logger:
  default: info
  logs:
    #homeassistant.components.automation: debug
    homeassistant.components.unifi: debug
    homeassistant.components.unifi.device_tracker: debug
    homeassistant.components.switch.unifi: debug

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Enable config UI
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

apcupsd:
  host: 192.168.1.1

sensor:
  - platform: apcupsd
    resources:
      - apc
      - date
      - hostname
      - upsname
      - upsmode
      - starttime
      - model
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
# Weather Prediction
#  - platform: yr
#  - platform: yweather
#    monitored_conditions:
#      - weather
#      - weather_current
#      - temp_min
#      - temp_max
#      - temperature
#      - humidity
#    forecast: 0
#  - platform: template
#    sensors:
#      temperature_difference:
#        value_template: '{{ (states.sensor.downstairs_temperature.state|float - states.sensor.upstairs_temperature.state|float)|abs|round(2) }}'
#        friendly_name: 'Temperature Difference'
#        unit_of_measurement: '°F'

hue:
  bridges:
    - host: 192.168.1.42
      allow_hue_groups: False

light:
  - platform: decora_wifi
    username: namniart@gmail.com
    password: !include leviton_password.yaml

tplink:
  discovery: True

ecobee: !include ecobee.yaml

device_tracker:
  - platform: unifi
    host: 192.168.1.1
    username: homeassistant
    verify_ssl: False
    site_id: default
    password: !include unifi_password.yaml
    new_device_defaults:
      track_new_devices: false

#influxdb:

automation: !include automations.yaml
automation old: !include_dir_merge_list automations

media_player:
  - platform: yamaha
    host: 192.168.1.63



group: !include groups.yaml
