lights_off:
  alias: Lights Off
  sequence:
  - service: light.turn_off
    data: {}
    target:
      entity_id: all
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.deck_light
      - switch.great_room_porch
      - switch.laundry
      - switch.outside_laundry
      - switch.back_door_light
  mode: single
  icon: mdi:lightbulb-group-off
bedtime:
  alias: Bedtime
  sequence:
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - bar_room
      - dining_room
      - downstairs_hall
      - great_room
      - hallway
      - kitchen
      - living_room
      - mechanical_room
      - stairs
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.deck_light
      - switch.great_room_porch
      - switch.laundry
      - switch.outside_laundry
      - switch.back_door_light
  mode: single
  icon: mdi:lightbulb-group-off
turn_down_lights:
  alias: Turn Down Lights
  sequence:
  - repeat:
      for_each:
      - light.bar
      - light.bar_2
      - light.bar_hallway
      - light.dining_room
      - light.dining_room_2
      - light.dining_table
      - light.downstairs_hall
      - light.fireplace_lights
      - light.great_room_light
      - light.hall_light
      - light.hue_color_lamp_1
      - light.hue_color_lamp_1_2
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
      - light.hue_lightstrip_1
      - light.island_pendants
      - light.kitchen
      - light.living_room_lights
      - light.living_room_walkway
      - light.stair_light
      - light.undercab_lights
      sequence:
      - if:
        - condition: template
          value_template: '{{ is_state(repeat.item, "on") and (state_attr(repeat.item,
            "brightness")|int > 64) }}'
        then:
        - service: light.turn_on
          target:
            entity_id: '{{ repeat.item }}'
          data:
            brightness: 64
  mode: single
  icon: mdi:lightbulb-night-outline
dining_blinds_down:
  alias: Dining Blinds Down
  sequence:
  - service: remote.send_command
    data:
      device: blinds
      command: down
    target:
      entity_id: remote.dining_room_remote
  mode: single
  icon: mdi:blinds
dining_blinds_up:
  alias: Dining Blinds Up
  sequence:
  - service: remote.send_command
    data:
      device: blinds
      command: up
    target:
      entity_id: remote.dining_room_remote
  mode: single
  icon: mdi:blinds-open
great_room_blinds_down:
  alias: Great Room Blinds Down
  sequence:
  - service: remote.send_command
    data:
      device: blinds
      command: down
    target:
      entity_id: remote.family_room_remote
  mode: single
  icon: mdi:blinds
great_room_blinds_up:
  alias: Great Room Blinds Up
  sequence:
  - service: remote.send_command
    data:
      device: blinds
      command: up
    target:
      entity_id: remote.family_room_remote
  mode: single
  icon: mdi:blinds-open
